apiVersion : apps/v1
kind: Deployment
metadata:
  name: "fridaydemojpguerra-0c95"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "fridaydemojpguerra-0c95"
  template:
    metadata:
      labels:
        app: "fridaydemojpguerra-0c95"
    spec:
      containers:
        - name: "fridaydemojpguerra-0c95"
          image: "juguerra.azurecr.io/fridaydemojpguerra"
          ports:
          - containerPort: 3000