apiVersion: v1
kind: Service
metadata:
    name: "fridaydemojpguerra-0c95"
    labels:
        app: "fridaydemojpguerra-0c95"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "fridaydemojpguerra-0c95"