on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: juguerra.azurecr.io
        username: ${{ secrets.acr_juguerra_username }}
        password: ${{ secrets.acr_juguerra_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t juguerra.azurecr.io/fridaydemojpguerra:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push juguerra.azurecr.io/fridaydemojpguerra:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_fridaydemojpguerra_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep fridaydemo | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace fridaydemo`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: fridaydemo
        container-registry-url: juguerra.azurecr.io
        container-registry-username: ${{ secrets.acr_juguerra_username }}
        container-registry-password: ${{ secrets.acr_juguerra_password }}
        secret-name: fridaydemojpdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: fridaydemo
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          juguerra.azurecr.io/fridaydemojpguerra:${{ github.sha }}
        imagepullsecrets: |
          fridaydemojpdockerauth
